<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">regexSplit</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCi8vIHJlZ2V4U3Bs
aXQgLSBwZXJmb3JtcyBhIHByb3BlciBzcGxpdCBvZiBhIHN0cmluZyB1c2luZyByZWdleCAodGhl
IHN0YW5kYXJkIGphdmEgdG9rZW5pemUgbWV0aG9kDQovLwkJCQloYXMgYSBIVUdFIGJ1ZyBpbiBp
dCB3aGVyZSBibGFuayBzdHJpbmdzIGFyZSByZW1vdmVkKQ0KLy8NCi8vCQlpbnB1dCAoaW5wdXQs
cmVxKSAtIHRoZSBpbnB1dCBzdHJpbmcgdG8gc3BsaXQNCi8vCQlyZWdleCAoaW5wdXQscmVxKSAt
IHJlZ3VsYXIgZXhwcmVzc2lvbiAob3IganVzdCBhIGNoYXJhY3RlciBvbiB3aGljaCB0byBzcGxp
dCkNCi8vCQlsaW1pdCAoaW5wdXQsb3B0KSAtIDwwIG9yIG51bGwgbWVhbnMgbm8gbGltaXQgKGRl
ZmF1bHQpDQovLwkJCQkJCQkwIG1lYW5zIG5vIGxpbWl0IGJ1dCB0cmFpbGluZyBlbXB0eSBzdHJp
bmdzIHdpbGwgYmUgcmVtb3ZlZA0KLy8JCQkJCQkJPjAgdXBwZXIgbGltaXQgb2Ygc3BsaXQgKG1h
eGltdW0gbnVtYmVyIG9mIGl0ZW1zIGdlbmVyYXRlZCkNCi8vDQovLwkJaXRlbXMgKG91dHB1dCxh
cnJheSkgLSBhIHN0cmluZyBsaXN0IG9mIHRoZSBzcGxpdCBpdGVtcw0KLy8JCWxlbmd0aCAob3V0
cHV0LHN0cikgLSB0aGUgc2l6ZSBvZiB0aGUgaXRlbXMgYXJyYXkNCg0KU3RyaW5nIGlucHV0ID0g
bnVsbDsNClN0cmluZyByZWdleCA9IG51bGw7DQpTdHJpbmcgbGltaXQgPSBudWxsOw0KaWYgKGN1
cnNvci5maXJzdCgiaW5wdXQiKSkgaW5wdXQgPSAoU3RyaW5nKSBjdXJzb3IuZ2V0VmFsdWUoKTsN
CmlmIChpbnB1dCA9PSBudWxsKSB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigicmVnZXhTcGxp
dDogTWlzc2luZyBpbnB1dCAnaW5wdXQnIik7IA0KaWYgKGN1cnNvci5maXJzdCgicmVnZXgiKSkg
cmVnZXggPSAoU3RyaW5nKSBjdXJzb3IuZ2V0VmFsdWUoKTsNCmlmIChyZWdleCA9PSBudWxsKSB0
aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigicmVnZXhTcGxpdDogTWlzc2luZyBpbnB1dCAncmVn
ZXgnIik7IA0KaWYgKGN1cnNvci5maXJzdCgibGltaXQiKSkgbGltaXQgPSAoU3RyaW5nKSBjdXJz
b3IuZ2V0VmFsdWUoKTsNCmlmIChsaW1pdCA9PSBudWxsKSBsaW1pdCA9ICItMSI7IA0KDQovL1Bh
dHRlcm4gcGF0dGVybiA9IFBhdHRlcm4uY29tcGlsZShyZWdleCk7DQovL1N0cmluZyBpdGVtc1td
ID0gcGF0dGVybi5zcGxpdChpbnB1dCk7DQpTdHJpbmcgaXRlbXNbXSA9IGlucHV0LnNwbGl0KHJl
Z2V4LCBJbnRlZ2VyLnBhcnNlSW50KGxpbWl0KSk7DQppbnQgbGVuZ3RoID0gaXRlbXMubGVuZ3Ro
Ow0KDQpJRGF0YVV0aWwucHV0KGN1cnNvciwgIml0ZW1zIiwgaXRlbXMpOw0KSURhdGFVdGlsLnB1
dChjdXJzb3IsICJsZW5ndGgiLCAiIiArIGxlbmd0aCk7DQpjdXJzb3IuZGVzdHJveSgpOw==</value>
</Values>
