<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">ifNull</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCi8vIGlmTnVsbCAt
IHJldHVybiBhIHN1cHBsaWVkIHZhbHVlIGlmIGFuIGlucHV0IHN0cmluZyBpcyBudWxsDQovLw0K
Ly8JCXN0cmluZyAoaW5wdXQscmVxKSAtIGEgc3RyaW5nIHRvIHRlc3QNCi8vCQl2YWx1ZSAoaW5w
dXQscmVxKSAtIHRoZSByZXBsYWNlbWVudCB2YWx1ZSBpZiAnc3RyaW5nJyBpcyBudWxsDQovLw0K
Ly8JCW5ld3N0cmluZyAob3V0cHV0LHN0cikgLSBhIHN0cmluZyBjb250YWluaW5nIGVpdGhlciAn
c3RyaW5nJyBvciAndmFsdWUnIGlmICdzdHJpbmcnIGlzIG51bGwNCi8vDQpTdHJpbmcgc1N0cmlu
ZyA9IG51bGw7DQpTdHJpbmcgc1ZhbHVlID0gbnVsbDsNCg0KaWYgKGN1cnNvci5maXJzdCgic3Ry
aW5nIikpIHNTdHJpbmcgPSAoU3RyaW5nKSBjdXJzb3IuZ2V0VmFsdWUoKTsNCmlmIChjdXJzb3Iu
Zmlyc3QoInZhbHVlIikpIHNWYWx1ZSA9IChTdHJpbmcpIGN1cnNvci5nZXRWYWx1ZSgpOw0KDQpp
ZiAoc1N0cmluZyA9PSBudWxsKSB7DQoJaWYgKHNWYWx1ZSA9PSBudWxsKSB0aHJvdyBuZXcgU2Vy
dmljZUV4Y2VwdGlvbigiaWZOdWxsOiBNaXNzaW5nIGlucHV0ICd2YWx1ZSciKTsNCglJRGF0YVV0
aWwucHV0KGN1cnNvciwgIm5ld3N0cmluZyIsIHNWYWx1ZSk7DQp9ZWxzZXsNCglJRGF0YVV0aWwu
cHV0KGN1cnNvciwgIm5ld3N0cmluZyIsIHNTdHJpbmcpOw0KfQ0KDQpjdXJzb3IuZGVzdHJveSgp
Ow==</value>
</Values>
