<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getCurrentTimeInMilliseconds</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCi8vIGdldEN1cnJl
bnRUaW1lSW5NaWxsaXNlY29uZHMgLSBnZXQgdGhlIGN1cnJlbnQgdGltZSBhcyBhIGxpbmVhciBu
dW1lcmljIHZhbHVlIGluIG1pbGxpc2Vjb25kcw0KLy8NCi8vCQlUaGUgdmFsdWUgcmV0dXJuZWQg
aXMgdGhlIG51bWJlciBvZiBtaWxsaXNlY29uZHMgc2luY2UgSmFudWFyeSAxc3QsIDE5NzAgYXQg
bWlkbmlnaHQgVVRDLiAgSXQgaXMgTk9UIGFuIGFjY3VyYXRlDQovLwkJcmVwcmVzZW50YXRpb24g
b2YgdGhlIGN1cnJlbnQgdGltZSwgc2luY2UgbGVhcCBzZWNvbmRzIGFyZSBub3QgdGFrZW4gaW50
byBjb25zaWRlcmF0aW9uLiAgSW5zdGVhZCBpdCBpcyBhIHNpbXBsZQ0KLy8JCWxpbmVhciwgYWx3
YXlzIGluY3JlYXNpbmcsIG51bWVyaWMgdmFsdWUgdGhhdCBjYW4gYmUgdXNlZCBtYXRoZW1hdGlj
YWxseSwgaWUsIGZvciBkZXRlcm1pbmluZyBlbGFwc2VkIHRpbWVzLiAgVGhlDQovLwkJdmFsdWUg
cmV0dXJuZWQgaXMgYSA2NC1iaXQgbG9uZywgd2hpY2ggaGFzIGFuIHVwcGVyIGxpbWl0IG9mIDJe
NjMtMS4gIER1cmluZyB0aGUgeWVhciAyMDE4LCB0aGUgcmFuZ2Ugb2YgdmFsdWVzDQovLwkJcmV0
dXJuZWQgaXMgcm91Z2hseSBiZXR3ZWVuIDEsNTE0LDgwMCwwMDAsMDAwIGFuZCAxLDU0NiwzMDAs
MDAwLDAwMC4NCi8vDQovLwkJdGltZV9pbl9tc2VjIChvdXRwdXQsc3RyKSAtIHRoZSBudW1iZXIg
b2YgbWlsbGlzZWNvbmRzIHNpbmNlIDEvMS8xOTcwIGFzIGEgbG9uZw0KDQpsb25nIHQgPSBTeXN0
ZW0uY3VycmVudFRpbWVNaWxsaXMoKTsNCklEYXRhVXRpbC5wdXQoIGN1cnNvciwgInRpbWVfaW5f
bXNlYyIsIHQgKyAiIik7DQpjdXJzb3IuZGVzdHJveSgpOwkJ</value>
</Values>
