<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">hexToBytes</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCgkJDQpTdHJpbmcg
c1N0cmluZyA9IG51bGw7DQoJCQ0KaWYgKGN1cnNvci5maXJzdCgiaGV4U3RyaW5nIikpIHNTdHJp
bmcgPSAoU3RyaW5nKSBjdXJzb3IuZ2V0VmFsdWUoKTsNCg0KaWYgKHNTdHJpbmcgPT0gbnVsbCB8
fCBzU3RyaW5nLmxlbmd0aCgpID09IDApDQp7DQoJDQoJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRp
b24oIkhleCBTdHJpbmcgUGFyYW1ldGVyIGlzIG1pc3NpbmciKTsNCn0NCg0KICAgIGJ5dGVbXSBi
eXRlcyA9IG5ldyBieXRlW3NTdHJpbmcubGVuZ3RoKCkgLyAyXTsNCiAgICBmb3IgKGludCBpID0g
MDsgaSA8IHNTdHJpbmcubGVuZ3RoKCk7IGkgKz0gMikgew0KICAgICAgICBieXRlc1tpIC8gMl0g
PSAoYnl0ZSkgKChDaGFyYWN0ZXIuZGlnaXQoc1N0cmluZy5jaGFyQXQoaSksIDE2KSA8PCA0KSAr
IENoYXJhY3Rlci5kaWdpdChzU3RyaW5nLmNoYXJBdChpICsgMSksIDE2KSk7DQogICAgfQ0KICAN
CiAgIA0KCS8vSURhdGFVdGlsLnB1dChjdXJzb3IsICJuZXdTVHJpbmciLCBieXRlcy50b1N0cmlu
ZygpKTsNCiAgICBJRGF0YVV0aWwucHV0KGN1cnNvciwgImJ5dGVzIiwgYnl0ZXMpOw0KDQogDQoJ
DQoJY3Vyc29yLmRlc3Ryb3koKTsNCg0KCQ==</value>
</Values>
