<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">fileExists</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCi8vICBmaWxlRXhp
c3RzIC0gY2hlY2sgaWYgYSBmaWxlIGV4aXN0cyBvbiB0aGUgZmlsZSBzeXN0ZW0NCi8vDQovLwkJ
cGF0aEZpbGUgKGlucHV0LHJlcSkgLSBmdWxseSBxdWFsaWZpZWQgcGF0aCBhbmQgZmlsZW5hbWUN
Ci8vDQovLwkJZXhpc3RzIChvdXRwdXQsc3RyKSAtIHRydWUgb3IgZmFsc2UNCg0KU3RyaW5nIHNQ
YXRoZmlsZSA9IG51bGw7DQoNCmlmIChjdXJzb3IuZmlyc3QoInBhdGhGaWxlIikpIHNQYXRoZmls
ZSA9IChTdHJpbmcpIGN1cnNvci5nZXRWYWx1ZSgpOw0KaWYgKHNQYXRoZmlsZSA9PSBudWxsKSB0
aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiZmlsZUV4aXN0czogUmVxdWlyZWQgaW5wdXQgc3Ry
aW5nICdwYXRoRmlsZScgaXMgbWlzc2luZyIpOw0KDQpqYXZhLmlvLkZpbGUgZnBUZXN0ID0gbmV3
IEZpbGUoc1BhdGhmaWxlKTsNCmlmIChmcFRlc3QuZXhpc3RzKCkgJiYgZnBUZXN0LmlzRmlsZSgp
ICkgew0KCUlEYXRhVXRpbC5wdXQoIGN1cnNvciwgImV4aXN0cyIsICJ0cnVlIik7DQp9ZWxzZXsN
CglJRGF0YVV0aWwucHV0KCBjdXJzb3IsICJleGlzdHMiLCAiZmFsc2UiKTsNCn0NCmN1cnNvci5k
ZXN0cm95KCk7</value>
</Values>
