<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">mkDir</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCi8vICBta0RpciAt
IGNyZWF0ZSBhIGZvbGRlcg0KLy8NCi8vCQlkaXJlY3RvcnkgKGlucHV0LHJlcSkgLSBmdWxseSBx
dWFsaWZpZWQgcGF0aA0KLy8NCi8vCQlzdGF0dXMgKG91dHB1dCxzdHIpIC0gdHJ1ZSBpZiBpdCB3
YXMgY3JlYXRlZCwgZmFsc2UgaWYgaXQgYWxyZWFkeSBleGlzdGVkIA0KDQpTdHJpbmcgc0ZvbGRl
ciA9IG51bGw7DQpib29sZWFuIHN0YXR1cyA9IGZhbHNlOw0KDQppZiAoY3Vyc29yLmZpcnN0KCJk
aXJlY3RvcnkiKSkgc0ZvbGRlciA9IChTdHJpbmcpIGN1cnNvci5nZXRWYWx1ZSgpOw0KaWYgKHNG
b2xkZXIgPT0gbnVsbCkgdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oIm1rRGlyOiBSZXF1aXJl
ZCBpbnB1dCBzdHJpbmcgJ2RpcmVjdG9yeScgaXMgbWlzc2luZyIpOw0KDQpGaWxlIHNGb2xkZXJT
cGVjID0gbmV3IGphdmEuaW8uRmlsZShzRm9sZGVyKTsNCmlmICghc0ZvbGRlclNwZWMuZXhpc3Rz
KCkpIHsNCiAgIHN0YXR1cyA9IHNGb2xkZXJTcGVjLm1rZGlycygpOw0KfQ0KSURhdGFVdGlsLnB1
dCggY3Vyc29yLCAic3RhdHVzIiwgc3RhdHVzICsgIiIpOw0KY3Vyc29yLmRlc3Ryb3koKTs=</value>
</Values>
