<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">stringToPdfBytearray</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCi8vIFRoaXMgc2Vy
dmljZSB0YWtlcyBhbiBpbnB1dCBzdHJpbmcgImNvbnRlbnQiIGFuZCBtYWtlcyBhIHBkZiBvdXQg
b2YgaXQNCi8vIFRoZSBvdXRwdXQgaXMgdGhlIGJ5dGVhcnJheSBvZiB0aGUgcGRmDQoNClN0cmlu
ZyBzQ29udGVudCA9IG51bGw7DQppZiAoY3Vyc29yLmZpcnN0KCJzdHJpbmciKSkgc0NvbnRlbnQg
PSAoU3RyaW5nKSBjdXJzb3IuZ2V0VmFsdWUoKTsNCmlmIChzQ29udGVudCA9PSBudWxsKSB0aHJv
dyBuZXcgU2VydmljZUV4Y2VwdGlvbigibG9naW46IE1pc3NpbmcgaW5wdXQgJ3N0cmluZyciKTsN
Cg0KdHJ5IHsNCgkNCglCeXRlQXJyYXlPdXRwdXRTdHJlYW0gc3RyZWFtID0gbmV3IEJ5dGVBcnJh
eU91dHB1dFN0cmVhbSgpOw0KCVBkZldyaXRlciB3cml0ZXIgPSBuZXcgUGRmV3JpdGVyKHN0cmVh
bSk7DQoJUGRmRG9jdW1lbnQgcGRmID0gbmV3IFBkZkRvY3VtZW50KHdyaXRlcik7DQoJRG9jdW1l
bnQgZG9jdW1lbnQgPSBuZXcgRG9jdW1lbnQocGRmKTsNCglkb2N1bWVudC5hZGQobmV3IFBhcmFn
cmFwaChzQ29udGVudCkpOw0KCWRvY3VtZW50LmNsb3NlKCk7DQoJDQoJSURhdGFVdGlsLnB1dChj
dXJzb3IsICJieXRlYXJyYXkiLCBzdHJlYW0udG9CeXRlQXJyYXkoKSk7DQoJDQoJICAgIA0KfSBj
YXRjaCAoRXhjZXB0aW9uIGUpIHsNCgkNCn0NCgkJDQpjdXJzb3IuZGVzdHJveSgpOw==</value>
</Values>
